### ISSUE TITLE
Possible Environmental variables?

### ISSUE THREAD

**Issue by Peter-The-Great** [doublesecretagency/craft-digitaldownload#11]
Is there a possibility to include or add Environmental variable support in the plugin?

**Comment by Peter-The-Great** [comment]
I have found a solution. In the services folder, in file Download.php, at line 171 or where the variable volumePath is declared. Use Craft::parseEnv() instead of Craft:: getAlias(). This function will not only search for Environmental variables, but will also look for aliases if no Environmental variables are found.

Code: $volumePath = Craft::parseEnv($volumeSettings['path']).'/';

**Comment by Peter-The-Great** [comment]
I think will just make a Pull request if you don't mind.

**Comment by lindseydiloreto** [comment]
Fixed in your PR #12, publicly released in **v2.1.8**. Thanks!
