### ISSUE TITLE
Craft / Commerce 4 support

### ISSUE THREAD

**Issue by rob-c-baker** [doublesecretagency/craft-digitaldownload#13]
Just wondering if there is a plan to make a release for support of Craft & Commerce `4.x` support?

**Comment by lindseydiloreto** [comment]
Yup, absolutely! We'll be porting all of our plugins to Craft 4 over the next few weeks.

**Comment by lindseydiloreto** [comment]
This is done! You can now update to **v2.2.0**, which is fully compatible with Craft 4. 👍
