### ISSUE TITLE
Setting options for file download

### ISSUE THREAD

**Issue by wallythewebdev** [doublesecretagency/craft-digitaldownload#15]
Hi I am trying to set a max download for an asset. 

Could you please provide the required format setting a maxDownload option for an asset. I've tried a few different ways to set options, all of which have failed. The download link is generated, but I am able to download the ASSET multiple times. I have tried a few variations but would appreciate just being told the correct format. 

```
        {# Get file #}
        {% set file = craft.assets().fileName('<FILE NAME HERE>').one() %}
        
        {# Set token #}
        {% set tokenPlugin = craft.digitalDownload.createToken(file, ['P14D', 1]) %}

        {# Provide link for user #}
        <a href="{{ craft.digitalDownload.url(tokenPlugin) }}">{{ file.title }}</a>
```

Thanks for your help
W

**Comment by wallythewebdev** [comment]
`{% set tokenPlugin = craft.digitalDownload.createToken(file, {"maxDownloads":"1"}) %}`

**Comment by lindseydiloreto** [comment]
Great, glad you got it sorted out! I just added an example to the documentation, to make it clearer for folks in the future...

https://plugins.doublesecretagency.com/digital-download/creating-a-token/
