### ISSUE TITLE
Downloads the page data not the file

### ISSUE THREAD

**Issue by wallythewebdev** [doublesecretagency/craft-digitaldownload#16]
Hi, 

I have ben using this plugin on a staging site to test before moving it onto the live site. 
The plugin is a trail right now (maybe that is the issue?) 

When trying to download the file which has been tokenised through the plugin, it downloads the page html file not the actual file

The below code **when not tokenising works** - so I don't think it is the file path otherwise this would not work? 

      {% set file = craft.assets().fileName('<file name>').one() %}

      <h2>Download: {{ file.title }}</h2>
      
      <a href="{{ file.url }}" download>{{ file.title }} - plane download</a>

When adding it to digital download to hide the address of the file - it then downloads the page instead of the  file: 

        <section>
          {% set tokenPlugin = craft.digitalDownload.createToken(file) %}
          <a href="{{ craft.digitalDownload.url(tokenPlugin) }}" download>Download: {{ file.title }}</a>
        </section>

Any help on this issue or pointing out what it might be would be great as i've got a pretty close deadline with this workflow. 
Thanks - W

**Comment by wallythewebdev** [comment]
The above is not working because for some reason - digital downloads is appending the URL of the download link with a pre existing token. 

I am providing a token to the user, which routes them to a page where the download is avalible. 

i.e. 

    {% set token = craft.app.tokens.createToken(['templates/render', {template: "/downloads/_one-pager"}]) %}
    <a href="{{siteUrl}}downloads/index?token={{ token }}" target="_blank">Visit our downloads page</a>

But on the downloads page (ref the code above)

The download URL is being presented as: 

`<a href="<website address>/download/nvxvfyprcpvyagmgcvlgndsruwhdabhntdlp?token=tNLj64aHEnRGmXxs3YEVPaIPopRPL8Ew" download="">DOWNLOAD Full - works on dev</a>`

So the digital downloads is appending the current web addresses token to the end of the URL for the download. 

Any ideas on removing this? 

Thanks

**Comment by lindseydiloreto** [comment]
I'd recommend removing the `download` attribute. It's not necessary, and might be causing the problem.

Try writing your link like this...

```twig
<a href="{{ craft.digitalDownload.url(token) }}">Download</a>
```

Here are the relevant docs...

https://plugins.doublesecretagency.com/digital-download/displaying-a-link/#manual-token-generation

Hope that helps, let me know if you have any follow-up questions!
