### ISSUE TITLE
"Cloud assets require a public URL." on an S3 asset?

### ISSUE THREAD

**Issue by jacobgraf** [doublesecretagency/craft-digitaldownload#6]
I was hoping to use this plugin to generate a secure link to an asset hosted on an S3 Asset Volume, but I just get the error `Cloud assets require a public URL.`. In the Asset settings, I have `Assets in this volume have public URLs` turned off because it's an S3 file and not locally hosted but the asset I am trying to access on S3 is world readable.

Am I missing something or are S3 assets not compatible with this plugin?

**Comment by lindseydiloreto** [comment]
`Cloud assets require a public URL` is meant to be taken quite literally. You'll need to enable the `Assets in this volume have public URLs` setting for it to work properly.

Hope that helps!

**Comment by jacobgraf** [comment]
Yes, but that setting isn't used when using an S3 volume. That's the whole point of my issue.

**Comment by lindseydiloreto** [comment]
Why not? Turning it on will fix your issue.

**Comment by jacobgraf** [comment]
But it's a required value, so what do I put in the Base URL field if it's an Amazon S3 volume? I tried hard-coding my s3 bucket URL in there but that didn't work either.

**Comment by lindseydiloreto** [comment]
Yours may be slightly different, but mine tend to look like this...

```
https://s3.us-west-1.amazonaws.com/bucketname/
```
